org: uybv91
app: wgs
service: wgs-app-api
frameworkVersion: '2'

custom:
  prefix: 'wgs-${sls:stage}'

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-1
  lambdaHashingVersion: '20201221'
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: 'arn:aws:dynamodb:ap-northeast-1:*:*'
  environment:
    NODE_ENV: ${sls:stage}

plugins:
  - serverless-plugin-typescript 
  - serverless-offline

package:
  exclude:
    - config/.env.stg
    - config/.env.pro
  include:
    - config/.env.dev

functions:
  api:
    handler: src/handler.handler
    name: wgs-app-api-${sls:stage}
    description: WGS API via Serverless Framework
    events:
      - httpApi: '*'

